### ISSUE TITLE
閃屏問題

### ISSUE THREAD

**Issue by garyopen1876** [monosparta/luck-cms#52]
網頁會定時閃屏
![Google-Chrome-2022-06-03-20-23-3 (1)](https://user-images.githubusercontent.com/32414355/171870857-d194bf6e-bd85-4b47-8213-b1d24746d079.gif)
▲示意圖

**Comment by rj1110634028** [comment]
嗯... 那是loading的效果，只是公司網路太順所以只閃一下:rofl:

**Comment by tildalu** [comment]
右邊的 Project 要選一下喔！
