### ISSUE TITLE
要不要考慮加入+886的電話格式

### ISSUE THREAD

**Issue by rj1110634028** [monosparta/luck-cms#54]
如題
![image](https://user-images.githubusercontent.com/48669926/171873565-177f21fb-2f3f-4857-aab6-cda420759975.png)

**Comment by rj1110634028** [comment]
> 如題 ![image](https://user-images.githubusercontent.com/48669926/171873565-177f21fb-2f3f-4857-aab6-cda420759975.png)

**Comment by tildalu** [comment]
右邊的 Project 要選一下喔！
