### ISSUE TITLE
測試強制開鎖時被通知要重新登入

### ISSUE THREAD

**Issue by MING-CHUNLee** [monosparta/luck-cms#56]
剛登入完不到3分鐘要輸入開鎖紀錄馬上就被通知要重新登入，不知道是不是Token期限設置太短
![image](https://user-images.githubusercontent.com/48669807/171900168-891ba157-1152-4b2e-818b-93756c8d4505.png)

**Comment by rj1110634028** [comment]
大概是被搶登了 現在只能一個人登入

**Comment by tildalu** [comment]
右邊的 Project 要選一下喔！
